# Generated by Django 4.1.7 on 2023-03-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('validation_code', models.CharField(max_length=6)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
