# Generated by Django 4.1.7 on 2023-03-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phonenumbervalidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbervalidation',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='phonenumbervalidation',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
