# Generated by Django 4.1.7 on 2023-03-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_phonenumbervalidation_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumbervalidation',
            name='verification_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
